### ISSUE TITLE
Problems with trial on OSX

### ISSUE THREAD

**Issue by kpoeck** [Shirakumo/trial#19] opened 2019-04-19 14:51 UTC
I tried to (ql:quickload :trial) on clasp (on OSX). After hitting some bugs in clasp (which are fixed now) i thumbled across the following problem:
```lisp
The parse rule TOKENIZE did not consume all of the tokens.
It is likely that it failed somewhere around . (position 164)
````
This is a continuable error, so if I select continue often enough, compilation comes to an end.

I tried a verify this with sbcl and ccl and to my surprise with both of them I get the same behaviour (getting continuable errors).

The error obviously come from glsl-toolkit
```lisp
(defun check-parse-complete (toplevel-rule)
  (when (/= *token-index* (length *token-array*))
    (cerror "Ignore the failure."
            "The parse rule ~a did not consume all of the tokens.~%~
             It is likely that it failed somewhere around ~a (position ~d)"
            toplevel-rule (peek) *token-index*)))
````

I understand that are not on my platform, but any hints on how to debug this?

**Comment by Shinmera** [comment] 2019-04-19 14:52
glsl-toolkit is platform-independent. What's the backtrace (including arguments/locals)?

**Comment by kpoeck** [comment] 2019-04-19 15:19
Here we go with sbcl
```lisp
karsten-poecks-macbook-pro:local-projects karstenpoeck$ sbcl
This is SBCL 1.5.1, an implementation of ANSI Common Lisp.
...
debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {10005385B3}>:
  The parse rule TOKENIZE did not consume all of the tokens.
It is likely that it failed somewhere around . (position 164)

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE                     ] Ignore the failure.
  1: [TRY-RECOMPILING              ] Recompile text and try loading it again
  2: [RETRY                        ] Retry
                                     loading FASL for #<CL-SOURCE-FILE "trial" "text">.
  3: [ACCEPT                       ] Continue, treating
                                     loading FASL for #<CL-SOURCE-FILE "trial" "text">
                                     as having been successful.
  4:                                 Retry ASDF operation.
  5: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  6:                                 Retry ASDF operation.
  7:                                 Retry ASDF operation after resetting the
                                     configuration.
  8: [ABORT                        ] Give up on "trial"
  9:                                 Exit debugger, returning to top level.

(GLSL-TOOLKIT:LEX #<(SIMPLE-ARRAY CHARACTER (206)) uniform vec4 objectcolor;
uniform sampler2D texture_image;
in vec2 texcoord;
out vec4 color;

void main(){
  float intensity = texture(texture_image, texcoord, -0.65).r;
  color = objectcolor * intens... {1005C95C2F}> GLSL-TOOLKIT:TOKENIZE)
   source: (CHECK-PARSE-COMPLETE TOPLEVEL-RULE)
backtrace

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {10005385B3}>
0: (GLSL-TOOLKIT:LEX #<(SIMPLE-ARRAY CHARACTER (206)) uniform vec4 objectcolor;
uniform sampler2D texture_image;
in vec2 texcoord;
out vec4 color;

void main(){
  float intensity = texture(texture_image, texcoord, -0.65).r;
  color = objectcolor * intens... {100644286F}> GLSL-TOOLKIT:TOKENIZE)
1: (GLSL-TOOLKIT:PARSE #<(SIMPLE-ARRAY CHARACTER (206)) uniform vec4 objectcolor;
uniform sampler2D texture_image;
in vec2 texcoord;
out vec4 color;

void main(){
  float intensity = texture(texture_image, texcoord, -0.65).r;
  color = objectcolor * intens... {100644286F}> GLSL-TOOLKIT:SHADER)
2: (COMBINE-SHADER-SOURCES #<(SIMPLE-ARRAY CHARACTER (206)) uniform vec4 objectcolor;
uniform sampler2D texture_image;
in vec2 texcoord;
out vec4 color;

void main(){
  float intensity = texture(texture_image, texcoord, -0.65).r;
  color = objectcolor * intens... {100644286F}>)
3: (SB-FASL::LOAD-FASL-GROUP #S(SB-FASL::FASL-INPUT :STREAM #<SB-SYS:FD-STREAM for "file /Users/karstenpoeck/.cache/common-lisp/sbcl-1.5.1-macosx-x64/Users/karstenpoeck/quicklisp/local-projects/trial/text.fasl" {100641CBA3}> :TABLE #(425 SET *PACKAGE* "ORG.SHIRAKUMO.FRAF.TRIAL" ERROR "FONT required." LAMBDA :IN #1="/Users/karstenpoeck/quicklisp/local-projects/trial/text.lisp" (LAMBDA NIL :IN #1#) #<SB-KERNEL:LAYOUT for SB-C::DEBUG-SOURCE {20301503}> #S(SB-C::DEBUG-SOURCE :NAMESTRING #1# :CREATED 3764650511 :COMPILED 3764675862 :PLIST NIL) ...) :STACK #(2 LIST 0 COMBINE-SHADER-SOURCES #<(SIMPLE-ARRAY CHARACTER (206)) uniform vec4 objectcolor;
uniform sampler2D texture_image;
in vec2 texcoord;
out vec4 color;

void main(){
  float intensity = texture(texture_image, texcoord, -0.65).r;
  color = objectcolor * intens... {100644286F}> (NIL NIL NIL) 72384 SB-PCL::FIND-CLASS-FROM-CELL 65600 SB-PCL::LOAD-DEFMETHOD 58432 STANDARD-METHOD ...) :NAME-BUFFER #("" "COMBINE-SHADER-SOURCESALL-FUNCTION") :DEPRECATED-STUFF NIL :SKIP-UNTIL NIL) NIL)
4: (SB-FASL::LOAD-AS-FASL #<SB-SYS:FD-STREAM for "file /Users/karstenpoeck/.cache/common-lisp/sbcl-1.5.1-macosx-x64/Users/karstenpoeck/quicklisp/local-projects/trial/text.fasl" {100641CBA3}> NIL NIL)
5: ((FLET SB-FASL::THUNK :IN COMMON-LISP:LOAD))
6: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<CLOSURE (FLET SB-FASL::THUNK :IN COMMON-LISP:LOAD) {5403CB}> #<SB-SYS:FD-STREAM for "file /Users/karstenpoeck/.cache/common-lisp/sbcl-1.5.1-macosx-x64/Users/karstenpoeck/quicklisp/local-projects/trial/text.fasl" {100641CBA3}>)
7: ((FLET SB-FASL::LOAD-STREAM :IN COMMON-LISP:LOAD) #<SB-SYS:FD-STREAM for "file /Users/karstenpoeck/.cache/common-lisp/sbcl-1.5.1-macosx-x64/Users/karstenpoeck/quicklisp/local-projects/trial/text.fasl" {100641CBA3}> T)
8: (COMMON-LISP:LOAD #P"/Users/karstenpoeck/.cache/common-lisp/sbcl-1.5.1-macosx-x64/Users/karstenpoeck/quicklisp/local-projects/trial/text.fasl" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
9: (UIOP/UTILITY:CALL-WITH-MUFFLED-CONDITIONS #<CLOSURE (LAMBDA NIL :IN UIOP/LISP-BUILD:LOAD*) {100641B5FB}> ("Overwriting already existing readtable ~S." #(#:FINALIZERS-OFF-WARNING :ASDF-FINALIZERS)))
10: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "trial" "text">)
11: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
12: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS (ASDF/LISP-ACTION:LOAD-OP ASDF/LISP-ACTION:CL-SOURCE-FILE)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "trial" "text">) [fast-method]
13: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "trial" "text">) [fast-method]
14: ((:METHOD ASDF/PLAN:PERFORM-PLAN (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {10070AA393}>) [fast-method]
15: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
16: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {10070AA393}>) [fast-method]
17: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "trial"> :PLAN-CLASS NIL :PLAN-OPTIONS NIL) [fast-method]
18: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "trial"> :VERBOSE NIL)
19: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
20: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "trial"> :VERBOSE NIL) [fast-method]
21: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/LISP-ACTION:LOAD-OP "trial" :VERBOSE NIL)
22: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
23: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP "trial" :VERBOSE NIL) [fast-method]
24: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<CLOSURE (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {100709B1DB}> :OVERRIDE T :KEY NIL :OVERRIDE-CACHE T :OVERRIDE-FORCING NIL)
25: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
26: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<CLOSURE (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {1006E9B15B}> :OVERRIDE NIL :KEY NIL :OVERRIDE-CACHE NIL :OVERRIDE-FORCING NIL)
27: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP "trial" :VERBOSE NIL) [fast-method]
28: (ASDF/OPERATE:LOAD-SYSTEM "trial" :VERBOSE NIL)
29: (QUICKLISP-CLIENT::CALL-WITH-MACROEXPAND-PROGRESS #<CLOSURE (LAMBDA NIL :IN QUICKLISP-CLIENT::APPLY-LOAD-STRATEGY) {1006E998AB}>)
30: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES "trial" :PROMPT NIL)
31: ((:METHOD QUICKLISP-CLIENT:QUICKLOAD (T)) :TRIAL :PROMPT NIL :SILENT NIL :VERBOSE T) [fast-method]
32: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<CLOSURE (LAMBDA NIL :IN QUICKLISP-CLIENT:QUICKLOAD) {100274131B}>)
33: (SB-INT:SIMPLE-EVAL-IN-LEXENV (QUICKLISP-CLIENT:QUICKLOAD :TRIAL :VERBOSE T) #<NULL-LEXENV>)
34: (EVAL (QUICKLISP-CLIENT:QUICKLOAD :TRIAL :VERBOSE T))
35: (SB-EXT:INTERACTIVE-EVAL (QUICKLISP-CLIENT:QUICKLOAD :TRIAL :VERBOSE T) :EVAL NIL)
36: (SB-IMPL::REPL-FUN NIL)
37: ((FLET "LAMBDA0" :IN "SYS:SRC;CODE;TOPLEVEL.LISP"))
38: (SB-IMPL::%WITH-REBOUND-IO-SYNTAX #<CLOSURE (FLET "LAMBDA0" :IN "SYS:SRC;CODE;TOPLEVEL.LISP") {541B7B}>)
39: (SB-IMPL::TOPLEVEL-REPL NIL)
40: (SB-IMPL::TOPLEVEL-INIT)
41: ((FLET SB-UNIX::BODY :IN SB-EXT:SAVE-LISP-AND-DIE))
42: ((FLET "WITHOUT-INTERRUPTS-BODY-7" :IN SB-EXT:SAVE-LISP-AND-DIE))
43: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))
````

**Comment by Shinmera** [comment] 2019-04-19 15:23
That doesn't show me the full source of the shader it's trying to compile.

**Comment by kpoeck** [comment] 2019-04-19 15:23
```lisp
list-locals
GLSL-TOOLKIT::INPUT  =  #<(SIMPLE-ARRAY CHARACTER (206)) uniform vec4 objectcolor;
uniform sampler2D texture_image;
in vec2 texcoord;
out vec4 color;

void main(){
  float intensity = texture(texture_image, texcoord, -0.65).r;
  color = objectcolor * intens... {100644286F}>
GLSL-TOOLKIT::TOPLEVEL-RULE  =  GLSL-TOOLKIT:TOKENIZE

0] 
````

**Comment by Shinmera** [comment] 2019-04-19 15:24
`intens...` means the string is abbreviated.

**Comment by kpoeck** [comment] 2019-04-19 15:24
oops, thats not full, one moment

**Comment by kpoeck** [comment] 2019-04-19 15:29
```c++
uniform vec4 objectcolor;
uniform sampler2D texture_image;
in vec2 texcoord;
out vec4 color;

void main(){
  float intensity = texture(texture_image, texcoord, -0.65).r;
  color = objectcolor * intensity;
}
````

**Comment by Shinmera** [comment] 2019-04-19 15:30
Can't reproduce. That string parses just fine with glsl-toolkit.

**Comment by Shinmera** [comment] 2019-04-19 15:32
If you just feed that string to `glsl-toolkit:parse` does it work?

**Comment by kpoeck** [comment] 2019-04-19 15:35
No
```lisp
* (GLSL-TOOLKIT:PARSE
"uniform vec4 objectcolor;
uniform sampler2D texture_image;
in vec2 texcoord;
out vec4 color;

void main(){
  float intensity = texture(texture_image, texcoord, -0.65).r;
  color = objectcolor * intensity;
}")

debugger invoked on a SIMPLE-ERROR in thread
#<THREAD "main thread" RUNNING {10005385B3}>:
  The parse rule TOKENIZE did not consume all of the tokens.
It is likely that it failed somewhere around . (position 164)

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE] Ignore the failure.
  1: [ABORT   ] Exit debugger, returning to top level.

(GLSL-TOOLKIT:LEX #<(SIMPLE-ARRAY CHARACTER (206)) uniform vec4 objectcolor;
uniform sampler2D texture_image;
in vec2 texcoord;
out vec4 color;

void main(){
  float intensity = texture(texture_image, texcoord, -0.65).r;
  color = objectcolor * intens... {1006A5F09F}> GLSL-TOOLKIT:TOKENIZE)
   source: (CHECK-PARSE-COMPLETE TOPLEVEL-RULE)
0] 
````

**Comment by Shinmera** [comment] 2019-04-19 15:36
I have no idea how that could happen. glsl-toolkit is just standard CL code that has nothing to do with the platform or the implementation.

**Comment by kpoeck** [comment] 2019-04-19 16:01
Perhaps the problem is the following:
```lisp
* (trace GLSL-PARSER-RULES:TOKENIZE )
(GLSL-PARSER-RULES:TOKENIZE)
* (GLSL-TOOLKIT:PARSE
"uniform vec4 objectcolor;
uniform sampler2D texture_image;
in vec2 texcoord;
out vec4 color;

void main(){
  float intensity = texture(texture_image, texcoord, -0.65).r;
  color = objectcolor * intensity;
}")
  0: (GLSL-PARSER-RULES:TOKENIZE)
  0: GLSL-PARSER-RULES:TOKENIZE returned
       (:UNIFORM :VEC4 "objectcolor" :|;| :UNIFORM :SAMPLER2D "texture_image"
        :|;| :IN :VEC2 "texcoord" :|;| :OUT :VEC4 "color" :|;| :VOID "main"
        :|(| :|)| :{ :FLOAT "intensity" := "texture" :|(| "texture_image" :|,|
        "texcoord" :|,| :- 0.65 :|)|)
````
Shoudn't that return also tokens for color = objectcolor * intensity;?

**Comment by Shinmera** [comment] 2019-04-19 16:05
Well yes, the lexer fails at that point for whatever reason, hence it not completely consuming the input.

**Comment by Shinmera** [comment] 2019-04-19 16:07
The only guess I have is #\Newline being different from LF. I pushed a fix for that, can you try again?

**Comment by kpoeck** [comment] 2019-04-19 16:17
Looks great:
```lisp
* (GLSL-TOOLKIT:PARSE
"uniform vec4 objectcolor;
uniform sampler2D texture_image;
in vec2 texcoord;
out vec4 color;

void main(){
  float intensity = texture(texture_image, texcoord, -0.65).r;
  color = objectcolor * intensity;
}")
(GLSL-TOOLKIT:SHADER
 (GLSL-TOOLKIT:VARIABLE-DECLARATION (GLSL-TOOLKIT:TYPE-QUALIFIER :UNIFORM)
  (GLSL-TOOLKIT:TYPE-SPECIFIER :VEC4) "objectcolor" GLSL-TOOLKIT:NO-VALUE)
 (GLSL-TOOLKIT:VARIABLE-DECLARATION (GLSL-TOOLKIT:TYPE-QUALIFIER :UNIFORM)
  (GLSL-TOOLKIT:TYPE-SPECIFIER :SAMPLER2D) "texture_image"
  GLSL-TOOLKIT:NO-VALUE)
 (GLSL-TOOLKIT:VARIABLE-DECLARATION (GLSL-TOOLKIT:TYPE-QUALIFIER :IN)
  (GLSL-TOOLKIT:TYPE-SPECIFIER :VEC2) "texcoord" GLSL-TOOLKIT:NO-VALUE)
 (GLSL-TOOLKIT:VARIABLE-DECLARATION (GLSL-TOOLKIT:TYPE-QUALIFIER :OUT)
  (GLSL-TOOLKIT:TYPE-SPECIFIER :VEC4) "color" GLSL-TOOLKIT:NO-VALUE)
 (GLSL-TOOLKIT:FUNCTION-DEFINITION
  (GLSL-TOOLKIT:FUNCTION-PROTOTYPE GLSL-TOOLKIT:NO-VALUE
   (GLSL-TOOLKIT:TYPE-SPECIFIER :VOID) "main")
  (GLSL-TOOLKIT:COMPOUND-STATEMENT
   (GLSL-TOOLKIT:VARIABLE-DECLARATION GLSL-TOOLKIT:NO-VALUE
    (GLSL-TOOLKIT:TYPE-SPECIFIER :FLOAT) "intensity" GLSL-TOOLKIT:NO-VALUE
    (GLSL-TOOLKIT:MODIFIED-REFERENCE "texture"
     (GLSL-TOOLKIT:CALL-MODIFIER "texture_image" "texcoord"
      (GLSL-TOOLKIT:NEGATION 0.65))
     (GLSL-TOOLKIT:FIELD-MODIFIER "r")))
   (GLSL-TOOLKIT:ASSIGNMENT "color" :=
    (GLSL-TOOLKIT:MULTIPLICATION "objectcolor" "intensity")))))
````
and no errors load trial
```lisp
(ql:quickload :trial :verbose t)
...
(:TRIAL)
````

**Comment by Shinmera** [comment] 2019-04-19 16:17
Crazy. Thanks for the report!

**Closed by Shinmera** 2019-04-19 16:17 UTC
